### ISSUE TITLE
Implement Content-Security-Policy header

### ISSUE THREAD

**Issue by notdryft** [warlegend/theme#105]

**Comment by notdryft** [comment]
http://content-security-policy.com/

**Comment by notdryft** [comment]
https://github.com/h5bp/server-configs-apache/blob/master/src/security/content-security-policy.conf

**Comment by notdryft** [comment]
http://www.html5rocks.com/en/tutorials/security/content-security-policy/?redirect_from_locale=es

**Comment by denpxc** [comment]
j comprends pas pkoi ce serait la raison que des fois ca se lance et des fois non?

**Comment by notdryft** [comment]
Aucun, mais ça spam la console d'erreurs à cause de Twitch & Cie.

**Comment by notdryft** [comment]
Fuck this shit.
